fix: move all localnet config files inside localnet folder

diff --git a/localnet/kubernetes/manifests/envoy-proxy.yaml b/localnet/kubernetes/manifests/envoy-proxy.yaml
--- a/localnet/kubernetes/manifests/envoy-proxy.yaml
+++ b/localnet/kubernetes/manifests/envoy-proxy.yaml
@@ -18,11 +18,11 @@ spec:
         command: ["/bin/sh", "-c"]
         args:
           - |
-            if [ ! -f /etc/envoy/envoy.yaml ]; then echo 'envoy.yaml not found. Run `make copy-envoy-config` to generate it.' && exit 1; fi; /usr/local/bin/envoy -c /etc/envoy/envoy.yaml
+            if [ ! -f /etc/envoy/.envoy.yaml ]; then echo '.envoy.yaml not found. Run `make copy-envoy-config` to generate it.' && exit 1; fi; /usr/local/bin/envoy -c /etc/envoy/.envoy.yaml
         volumeMounts:
         - name: envoy-config
-          mountPath: /etc/envoy/envoy.yaml
-          subPath: envoy.yaml
+          mountPath: /etc/envoy/.envoy.yaml
+          subPath: .envoy.yaml
         ports:
         - containerPort: 3001
       volumes:
